app:
  security:
    enabled: false

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: PLAINTEXT
      ssl.keystore.location: ""
      ssl.keystore.password: ""
      ssl.truststore.location: ""
      ssl.truststore.password: ""
